### ISSUE TITLE
denzi_ - Any user can call `Admin.sol::destroyInstance()` and destroy a Token Sale Instance.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zap-protocol-judging#118]
denzi_

medium

# Any user can call `Admin.sol::destroyInstance()` and destroy a Token Sale Instance.

## Summary

Any user can call the `destroyInstance()` function in Admin.sol in `zap-contracts-labs` and destroy a token sale instance.

## Vulnerability Detail

`destroyInstance()` in `Admin.sol` exists to destroy existing, and incoming instances. This function is external and can be called by any user. This function does not implement a check whether the `msg.sender` is an admin/operator. 

The function calls `Admin.sol::_removeFromSales()` and then calls `TokenSale.sol::destroy()` function.

The `TokenSale.sol::destroy()` function calls `_onlyAdmin()` to check if the `msg.sender` is the admin, since the msg.sender inside this function is the `Admin.sol` contract (cross contract function call). The check passes and transfers assets to to the `admin.wallet()` and self destructs.

### Proof of Concept

Add the following function in `TokenSale.sol` to use the mockUSDC for testing purposes

```solidity
function setUSDC(address _newUSDC) public {
        usdc = IERC20D(_newUSDC);
    }
```

Add the following function after creating a foundry setup
```solidity
function testDeletePoolByAnyone() public {
        TokenSale(payable(tokenSaleInstance1)).setUSDC(address(mockUSDC));

        vm.prank(bob);
        adminContract.destroyInstance(payable(address(tokenSaleInstance1)));
        vm.stopPrank();
    }
```

[`Admin.t.sol` with the setup and test](https://pastebin.com/dQ7bVMuM)

## Impact

Although the function makes sure that an ongoing Token Sale Instance can not be destroyed but any user can grief the protocol by destroying newly created Instances causing the creator to redeploy the instance. This causes the creator to spend more gas to recreate the same instance.

## Code Snippet

[`Admin.sol::destroyInstance()`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/Admin.sol#L138-L143)

```solidity
function destroyInstance(
        address _instance
    ) external onlyExist(_instance) onlyIncoming(_instance) {
        _removeFromSales(_instance);
        ITokenSale(_instance).destroy();
    }
```

[`TokenSale.sol::destroy()`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L186-L194)

```solidity
function destroy() external override {
        _onlyAdmin();
        uint256 amountUSDC = usdc.balanceOf(address(this));
        if (amountUSDC > 0) {
            usdc.safeTransfer(admin.wallet(), amountUSDC);
        }
        address payable wallet = payable(admin.wallet());
        selfdestruct(wallet);
    }
```

## Tool used

Manual Review , Foundry

## Recommendation

Add the following `onlyAdmin` Modifier on `Admin.sol::destroyInstance()`

```diff
function destroyInstance(
        address _instance
-    ) external onlyExist(_instance) onlyIncoming(_instance)
+    ) external onlyExist(_instance) onlyIncoming(_instance) onlyAdmin {
        _removeFromSales(_instance);
        ITokenSale(_instance).destroy();
    }
```

**Comment by midori-fuse** [comment]
Escalate

As of dencun upgrade, `selfdestruct` is still usable, albeit its only effect is that it drains Ether balance of the contract to the target recipient (but does not delete any other data). See [EIP-6780](https://eips.ethereum.org/EIPS/eip-6780) and relevant discussion on #59 .

Since this `destroy()` function also drains USDC to the admin, the effect of this issue is then anyone can forcefully drain USDC to the admin and deny any other functions relying on USDC non-admin outward transfers. There is one such function, and is the function [`claim()`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L390).

The core issue here remains incorrect access control, and as opposed to the lead judge's comment, it does have an adverse effect, namely denying one core contract functionality, which qualifies for the Medium severity. Perhaps Watsons submitting this issue has not dig deep enough into EIP-6780, but this escalation is to show that there is a real impact arising from this issue.

Because I have not found a dupe that correctly identifies the related details, it is then up to the lead judge and head of judging to decide whether this family of issues is rewardable. I am only addressing the incorrect comment from the lead judge and providing facts to ensure the correct issue is realized, and fair judging is made.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Issue is valid, albeit requires some more details to be fully correct.
> 
> As of dencun upgrade, `selfdestruct` is still usable, albeit its only effect is that it drains Ether balance of the contract to the target recipient (but does not delete any other data). See [EIP-6780](https://eips.ethereum.org/EIPS/eip-6780) and relevant discussion on #59 .
> 
> Since this `destroy()` function also drains USDC to the admin, the effect of this issue is then anyone can forcefully drain USDC to the admin and deny any other functions relying on USDC non-admin outward transfers. There is one such function, and is the function [`claim()`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L390).
> 
> The core issue here remains incorrect access control, and as opposed to the lead judge's comment, it does have an adverse effect, namely denying one core contract functionality, which qualifies for the Medium severity. Perhaps Watsons submitting this issue has not dig deep enough into EIP-6780, but this escalation is to show that there is a real impact arising from this issue.
> 
> Because I have not found a dupe that correctly identifies the related details, it is then up to the lead judge and head of judging to decide whether this family of issues is rewardable. I am only addressing the incorrect comment from the lead judge and providing facts to ensure the correct issue is realized, and fair judging is made.
> 

You've deleted an escalation for this issue.

**Comment by 0xgivn** [comment]
Zap protocol is going to be deployed on Blast, which is built on top of the Bedrock OP stack.
> On what chains are the smart contracts going to be deployed?
> **Blast**

The EVM instruction set used on this L2 supports the old behavior of `selfdestruct`.

I've created a gist that showcases the issue, check out for yourself what happens with the deployed bytecode once `selfdestruct` is called:
https://gist.github.com/georgiIvanov/a82d6b4246526e44c52a332377cfe8ce

**Comment by midori-fuse** [comment]
> Zap protocol is going to be deployed on Blast, which is built on top of the Bedrock OP stack.
> 
> > On what chains are the smart contracts going to be deployed?
> > **Blast**
> 
> The EVM instruction set used on this L2 supports the old behavior of `selfdestruct`.
> 
> I've created a gist that can support this claim, check out for yourself what happens with the deployed bytecode once `selfdestruct` is called: https://gist.github.com/georgiIvanov/a82d6b4246526e44c52a332377cfe8ce

Interesting 👀 I certainly learn so much for being proven wrong.

Issue (and the escalation) actually still stands since there is a griefing factor as obviously anyone can destroy token sales. However my escalation details have been proven wrong, so I will edit it to the correct information.

Thanks a lot for your help, I certainly got a valuable lesson.

Edit: Eh, scratch that, I missed the part where ongoing sales can't be destroyed. If this is true then indeed there isn't a way to cause damage besides from constant griefing.

**Comment by Rcontre360** [comment]
Commenting that this is the main issue of issue [75](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/75)

**Comment by s1ce** [comment]
Escalate

This issue is valid. As mentioned above, an adversary can backrun TokenSale contract creations that have not yet started and destroy them. 

Additionally, note that `_removeFromSales` is called every time `destroyInstance` is called. `_removeFromSales` calls `tokenSales.pop()` everytime it is called, thus decreasing the size of `tokenSales` by 1. An adversary can call `destroyInstance` with an arbitrary address and force the size of `tokenSales` to decrease by 1, until it is empty and the `destroyInstance` function can't be called again. 

In short, there are two impacts:

1. Prevent admin from creating TokenSale contracts that start in the future
2. Prevent admin from ever calling `destroyInstance`

Because this issue does not cause a loss of user funds, but breaks protocol functionality, would recommend classifying it as medium

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is valid. As mentioned above, an adversary can backrun TokenSale contract creations that have not yet started and destroy them. 
> 
> Additionally, note that `_removeFromSales` is called every time `destroyInstance` is called. `_removeFromSales` calls `tokenSales.pop()` everytime it is called, thus decreasing the size of `tokenSales` by 1. An adversary can call `destroyInstance` with an arbitrary address and force the size of `tokenSales` to decrease by 1, until it is empty and the `destroyInstance` function can't be called again. 
> 
> In short, there are two impacts:
> 
> 1. Prevent admin from creating TokenSale contracts that start in the future
> 2. Prevent admin from ever calling `destroyInstance`
> 
> Because this issue does not cause a loss of user funds, but breaks protocol functionality, would recommend classifying it as medium

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by bG9zZXIvZmFpbHVyZQ** [comment]
Hi, comparing this issue/#76 and #157/#54. This issue is marked invalid because "destroy" is assumed to no longer be functional, hence calling `destroyInstance` function will not destroy the IDOs. How is issue #157 valid for a ".call" based re-entrancy if as issue #54 points out, the contract cannot receive ETH?

**Comment by ghost** [comment]
As far as I know transaction reverts, as selfdestruct is deprecated. I am unable to make sense of what @bG9zZXIvZmFpbHVyZQ is highlighting to? Would be great if you describe a bit more

**Comment by bG9zZXIvZmFpbHVyZQ** [comment]
Hi @Hash01011122 
I'm trying to make a comparison to the two sets of issues.  

#76 points out that the selfdestruct opcode is now deprecated, hence IDOs cannot be destroyed. Because of that fact, this issue is marked as invalid. 

Now, #54 points out that the vesting contract cannot receive ETH, hence marked as valid.
 But #157 points out that the vesting contract can be drained(i.e loss of funds) due to reentrancy, from the use of ".call" to transfer ETH. Also marked valid. 
The question is how can the contract be drained of ETH if it cannot receive ETH in the first place? 
I'm assuming it was marked as valid because of the reentrancy issue still present.

Should the same reasons not hold for this issue, as there's a lack of access control in the `destroyInstance` function?

**Comment by ZdravkoHr** [comment]
@Hash01011122, the contracts will be deployed on Blast where selfdestruct is operating as before Dencun. As a proof, you can take a look at [this contract](https://testnet.blastscan.io/address/0xa1931159cd756FfC6e6907f2aE49a127570994C5) I deployed on Blast Sepolia.

The contract is as simple as possible.

```solidity
pragma solidity 0.8.20;

contract MyContract {
    uint256 public a;

    constructor() {
        a = 50;
    }

    function destroy() public {
        selfdestruct(payable(address(0)));
    }
}
```

The status of my [destroy transaction](https://testnet.blastscan.io/tx/0x678047fc5acba63ef94e63fa90a16d546e00473329780d2eb6639d775946ecb1) is `success`. After it, if you try to query the value of `a` in the explorer, you receive an error instead of the default value of `50`, which shows that the contract has been destroyed successfully.

**Comment by 0xgivn** [comment]
> As far as I know transaction reverts, as selfdestruct is deprecated. I am unable to make sense of what @bG9zZXIvZmFpbHVyZQ is highlighting to? Would be great if you describe a bit more

Blast runs on the Cancun EVM instruction set, which supports deleting the bytecode of a contract.
There are multiple ways to verify this:
1. Check out [blast/op-geth](https://github.com/blast-io/blast/tree/master/blast-geth) - check the instruction set, no mention of dencun, only cancun. Here is what the [`SELFDESTRUCT`](https://github.com/blast-io/blast/blob/04ed82f54a627622f82bea2217a090106d1ca2c2/blast-geth/core/vm/instructions.go#L826-L841) opcode does, here's a [test](https://github.com/blast-io/blast/blob/04ed82f54a627622f82bea2217a090106d1ca2c2/blast-geth/core/state/state_test.go#L230-L242) for the behavior - objects marked as destructed are deleted when persisted on state.
2. Follow the instructions from my previous comment - deploy a contract on `blast.sepolia.testnet` and destroy it -> [here](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/118#issuecomment-2024997136).

To spell it literally - `selfdestruct` is deprecated, but still works by deleting the bytecode of a contract. Take this into account when reviewing escalations, please.

**Comment by ghost** [comment]
Even if we consider `selfdestruct` opcode valid due to the effect of cancun on Blast this issue will be borderline low/medium severity. I will let @Czar102 decide this one.

**Comment by shubham-antier** [comment]
We removed the function completely since the destroy function in TokenSale.sol was completely removed in issue #59

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Lithium-Ventures/zap-contracts-labs/pull/8

**Comment by Evert0x** [comment]
I believe this issue should stay invalid.

> Griefing for gas (frontrunning a transaction to fail, even if can be done perpetually) is considered a DoS of a single block, hence only if the function is clearly time-sensitive, it can be a Medium severity issue.

Planning to reject escalation and keep invalid

**Comment by s1ce** [comment]
@Evert0x Disagree with you:

1. It is time sensitive, as there is a start time associated with the TokenSale, and the attacker can continuously delete the TokenSale contract causing the sale to never start.
2. As I outlined in the escalation, another impact is to prevent the admin from ever calling `destroyInstance` by maliciously forcing the size of the `tokenSales` array to 0, which clearly destroys intended protocol behavior

**Comment by Evert0x** [comment]
1) The person can deploy a tokensale with an immediate start date, right? That will mitigate the problem
2) Agree that's a possibility, but it's not a reason to assign Medium severity

**Comment by s1ce** [comment]
@Evert0x An admin function not working at all is a breakage of protocol functionality, which Sherlock has historically categorized as medium severity.

**Comment by 0xDenzi** [comment]
@Evert0x 

> 1. The person can deploy a token sale with an immediate start date, right? That will mitigate the problem

Telling users to create token sales with an immediate start date or else they will be destroyed by any other user is not really a mitigation. Defeats the purpose of being able to customize token sales and setting them up as the person wants.

**Comment by Evert0x** [comment]
> The issue impacts the availability of time-sensitive functions **(cutoff functions are not considered time-sensitive)**

The start of the token sale is a cut-off function

**Comment by detectiveking123** [comment]
This one is pretty borderline; it's hard for me to say whether it's a low or a medium. But I'm leaning towards deeming it a low. While an admin function not working at all is indeed a breakage of protocol functionality, I am not sure this particular one is a breakage of **core** protocol functionality.

**Comment by ghost** [comment]
@s1ce I guess your 1st point of argument was covered by @Evert0x, 2nd impact of your argument isn't mentioned anywhere in any reports. Even if consider it, wouldn't it make it low to informational issue?

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [s1ce](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/118/#issuecomment-2026293430): rejected

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
