### ISSUE TITLE
denzi_ - Insufficient Validation on user inputs for `Admin.sol::createPoolNew` in `zap-launches-contracts` can lead to instances susceptible to DoS

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zap-protocol-judging#121]
denzi_

high

# Insufficient Validation on user inputs for `Admin.sol::createPoolNew` in `zap-launches-contracts` can lead to instances susceptible to DoS

## Summary

The `zap-launches-contracts` includes `Admin.sol` which provides permissionless creation of Token Sale Instances. Users can create TokenSales for either ETH based or USDB based using the `Admin.sol::createPoolNew()` function. The argument `_maxAllocation` and `_params.liqudityPercentage` can cause DoS when the creator/user calls the `takeUSDBRaised()` function in the instance due to insufficient validations on user input in `Admin.sol::createPoolNew()`.

## Vulnerability Detail

The user inputs `_params`, `_config`, `_maxAllocation`, `_isKYC`, and `isETHBased`. Out of these parameters the `_maxAllocation` and `_params.liqudityPercentage` can introduce DoS for the creator/user when calling `takeUSDBRaised()`. 

The checks performed in [`_checkingParams()`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-launches-contracts/contracts/Admin.sol#L208-L222) are insufficient which create possibility of DoS in the newly created instances.

### Case 1:

[Case 1 Code](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-launches-contracts/contracts/TokenSaleUSDB.sol#L197-L204)

The `_params.liquidityPercentage` is used to calculate the `earned` variable inside `takeUSDBRaised()`
```solidity
earned = (earned * (POINT_BASE - params.liqudityPercentage)) / POINT_BASE;
```
This earned value is then used in the following line of code to transfer the amount which is calculated
```solidity
USDB.safeTransfer(creator, earned - earning);
```

If the `_params.liquidityPercentage` is passed in by the user between `9955` to `10000` (inclusive), the `earned` value will be less than `earning` and the function `USDB.safeTransfer()` will revert.

#### Mathematical example
This is due to Rounding

```solidity
uint256 earned = state.totalSold > state.totalSupplyInValue
            ? state.totalSupplyInValue
            : state.totalSold;
```

Suppose `earned` here is `45` then we calculate earning and earned(again) inside the `if (earned > 0)`
```solidity
uint earning = (earned * (platformTax)) / POINT_BASE;
```
Suppose `earning` is `2`

```solidity
earned = (earned * (POINT_BASE - params.liqudityPercentage)) / POINT_BASE;
```
`earned = (45 * (10000 - 9556)) / 10000` becomes `1.998` which rounds down to `1`.
Substituting `earned - earning` i.e `1 - 2`, will result in an underflow causing the function to revert.

Note: Values above are taken from the PoC given down below

### Case 2:

[Case 2 Code](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-launches-contracts/contracts/TokenSaleUSDB.sol#L208)

The `_maxAllocation` argument decides the `state.totalSupplyInValue` and `tokenPrice` of the newly created Instance. On certain values of `_maxAllocation` i.e `_maxAllocation < 10000` The `tokenPrice` can become 0.

The `_maxAllocation` argument is used to calculate the `tokenPrice` using
```solidity
tokenPrice =
    (_maxAllocation * 10 ** IERC20D(params.tokenAddress).decimals()) / _params.totalSupply;
```

If the `tokenPrice` in the instance becomes 0, important division which uses `tokenPrice` as denominator will panic revert such as

```solidity
uint unsoldTokens = (unsold * (10 ** ETH_DECIMAL)) / tokenPrice;
```
this line will throw a panic error : division or modulo by zero causing the function to revert. 

### Proof of Concept

Add the following setUp in `Admin.t.sol`

```solidity
contract MockERC20D is ERC20 {
    constructor() ERC20("MockERC20D", "MERC20D") {}

    function mint(address to, uint256 amount) public {
        _mint(to, amount);
    }
}

interface ITokenSaleUSDB {
    function deposit(uint256 amount) external;

    function claim() external;

    function setUSDB(address) external;

    function takeUSDBRaised() external;
}

contract AdminTest is Test {
    address deployer = makeAddr("deployer");

    Admin admin;

    address creator = makeAddr("creator");
    address bob = makeAddr("bob");
    address alice = makeAddr("alice");

    address operator = makeAddr("operator");

    address wallet_ = makeAddr("wallet_");

    TokenSaleETH tokenSaleETH;
    TokenSaleUSDB tokenSaleUSDB;

    MockERC20D erc20d;

    uint256 constant STARTING_AMOUNT = 1 ether;

    address tokenSaleInstance;

    receive() external payable {}

    function setUp() public {
        deployer = address(this);

        admin = new Admin();

        admin.initialize(deployer);

        tokenSaleUSDB = new TokenSaleUSDB();

        admin.setMasterContractUSDB(address(tokenSaleUSDB));

        admin.grantRole(keccak256("OPERATOR"), operator);
        admin.grantRole(keccak256("OPERATOR"), address(this));

        erc20d = new MockERC20D();

        vm.deal(creator, 1 ether);
        erc20d.mint(creator, 100000e18);
        erc20d.mint(bob, 10000e18);
        erc20d.mint(alice, 10000e18);

        address tokenAddress = address(erc20d);
        address router = address(0x456);
        // Set up your ITokenSale.Params and ITokenSale.Config structs
        // Example values for Params
        ITokenSale.Params memory params = ITokenSale.Params({
            tokenAddress: tokenAddress,
            router: router,
            totalSupply: 10000e18,
            saleStart: uint96(block.timestamp + 1 days),
            saleEnd: uint96(block.timestamp + 5 days),
            liqudityPercentage: 9550,
            tokenLiquidity: 100e18,
            baseLine: 1e18,
            burnUnsold: false
        });

        // Example values for Config
        ITokenSale.Config memory config = ITokenSale.Config({
            LPLockin: 30 days,
            vestingPeriod: 90 days,
            vestingDistribution: 180 days,
            NoOfVestingIntervals: 6,
            FirstVestPercentage: 2000,
            LiqGenerationTime: uint96(block.timestamp + 11 days)
        });

        // Assume platformFee is set to 0.2 ether in the Admin contract
        uint256 platformFee = 0.2 ether;

        // Simulate sending the platform fee with the function call
        vm.prank(creator);
        erc20d.approve(address(admin), 100000e18);
        vm.stopPrank();

        vm.prank(creator);
        tokenSaleInstance = admin.createPoolNew{value: platformFee}(
            params,
            config,
            1000,
            false,
            false
        );
        vm.stopPrank();

        ITokenSaleUSDB(tokenSaleInstance).setUSDB(address(erc20d));
    }
}
```

Add the following test into the test contract
```solidity
function testUSDBRaised() public {
        vm.warp(block.timestamp + 1 days);

        // Approve and deposit for Bob

        vm.prank(bob);
        erc20d.approve(address(tokenSaleInstance), 10000);
        vm.stopPrank();

        vm.prank(bob);
        ITokenSaleUSDB(tokenSaleInstance).deposit(25);
        vm.stopPrank();

        // Approve and deposit for Alice
        vm.prank(alice);
        erc20d.approve(address(tokenSaleInstance), 10000);
        vm.stopPrank();

        vm.prank(alice);
        ITokenSaleUSDB(tokenSaleInstance).deposit(20);
        vm.stopPrank();

        // Move time forward to allow claiming
        vm.warp(block.timestamp + 6 days);

        ITokenSaleUSDB(tokenSaleInstance).takeUSDBRaised();
    }
```

### Case 1: 
Set the `liqudityPercentage` > `9555` and run the test.

### Case 2:
Set the `liqudityPercentage` <= `9555` and set `_maxAllocation` < `10000` run the test.

## Impact

The function `takeUSDBRaised()` is an important function which sets 
```solidity
isRaiseClaimed = true;
```  
This function is present in both the possible instances that can be created from the `Adminsol::createPoolNew()`

If `isRaiseClaimed` is not set to true, other users of the tokenSale will not be allowed to complete the calls to `claim()`, `addLiq()`, `claimLP()`, `vesting()`  function as these require `isRaiseClaimed` to be set as true.

This causes DoS for most of the functions of the Token Sale contracts and users are not able to execute their desired functions.

## Code Snippet

[Admin.sol::createPoolNew()](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-launches-contracts/contracts/Admin.sol#L288-L316)

[Admin.sol::_checkingParams](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-launches-contracts/contracts/Admin.sol#L208-L222)

[TokenSaleETH::takeUSDBRaised()](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-launches-contracts/contracts/TokenSaleETH.sol#L166-L188)

[TokenSaleUSDB::takeUSDBRaised()](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-launches-contracts/contracts/TokenSaleUSDB.sol#L192-L217)

## Tool used

Manual Review, Foundry

## Recommendation

Add the necessary checks for `_maxAllocation` and calculate/set the maximum allowed `_params.liquidityPercentage` in `Admin.sol::_checkingParams`

```diff
-function _checkingParams(ITokenSale.Params memory _params, ITokenSale.Config memory _config) internal view
+function _checkingParams(ITokenSale.Params memory _params, ITokenSale.Config memory _config, uint256 _maxAllocation) internal view
{
        require(_params.totalSupply > 0, "TokenSale: TotalSupply > 0");
        require(
            _params.saleStart >= block.timestamp,
            "TokenSale: Start time > 0"
        );
        require(
            _params.saleEnd > _params.saleStart,
            "TokenSale: End time > start time"
        );
-       require(_params.liqudityPercentage > 0 && _params.liqudityPercentage <= POINT_BASE,
-            "TokenSale: LiqudityPercentage Invalid");
+       require(_params.liqudityPercentage > 0 && _params.liqudityPercentage <= 9555, 
+            "TokenSale: LiqudityPercentage Invalid");
        require(_config.NoOfVestingIntervals > 0, "NoOfVestingIntervals can't be Zero");
        require(_config.FirstVestPercentage > 0, "FirstVestPercentage can't be Zero");
+       require(_maxAllocation >= 10000, "_maxAllocation can't be less than 10000");
    }
```

**Comment by 0xDenzi** [comment]
`Admin.sol` from zap-launches-contract is permissionless and allows users to create pools using `createPoolNew()` function and providing in parameters. The `_checkingParams(_params, _config);` line of code is used to call the function and validate the parameters entered by the user. The submission contains a detailed explanation of how some important parameters are not validated which allows the `createPoolNew()` to create `dodgy/faulty` pools.

Even though the instances are not part of scope, the `createPoolNew()` and `_checkingParams()` functions are part of scope and are important functions which are used in combination to create these instances. The checks exist so that the pools are properly configured and initialized. My submission provides detailed explanation of a vulnerability that starts from the in-scope contract and can be mitigated in the in-scope contract. The impact is made possible through the following lines of code

```solidity
ITokenSale(instance).initialize(
            _params,
            address(this),
            msg.sender,
            _maxAllocation,
            platformTax,
            _isKYC
        );
```

Through this initialize call the `tokenPrice` is set to `0` and `_params.liquidityPercentage` is passed

Further more, this allows users to create pools where deposits are possible but claiming and many other actions by users are not possible which creates an opportunity for users to have their funds locked. These pools can be created by malicious users if the right checks are not present in `_checkingParams()` function

P.S the deposits in PoC use low precision values but the issue exists even with high precision values by lowering the `_params.liquidityPercentage`

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Lithium-Ventures/zap-launches-contracts/pull/2

**Comment by ghost** [comment]
This is a valid medium @Czar102

**Comment by spacegliderrrr** [comment]
@Hash01011122 Nope, this is not. 1) it is an input mistake. 2) issue lies within Out-of-scope contracts.

**Comment by 0xDenzi** [comment]
> @Hash01011122 Nope, this is not. 1) it is an input mistake. 2) issue lies within Out-of-scope contracts.

1.Users can create faulty/dodgy pools that will get other user's funds locked. Suppose someone creates a token sale through the admin.sol by giving in such parameters with malicious intent of locking depositor's funds, this does not fall into input mistake.

2.The admin.sol which is in scope has two functions as mentioned above which create this issue. createPoolNew and _checkParams

The _checkParams function exists to validate the user inputs so that authentic token sales can be created. It is called right at the start of the createPoolNew function before creating an instance, the parameters mentioned are not validated/checked properly which leads to such instances being created.

The call to initialize an instance is in-scope which passes all the user given parameters.

In this contest we were given admin.sol to audit. Admin.sol is the entry point to creating instances and it was our task to verify all the functions inside this contract, I've simply explained a way for users to use admin.sol to create malicious pools, Keep in mind that the submission questions _checkParams and createPoolNew functions and how they do not disallow such pools from being created, The issue originates from the in-scope contract, the impact occurs through the createPoolNew and _checkParams functions. The mitigation for this issue is also done in the in-scope contract by adding the required checks.

**Comment by ghost** [comment]
Agreeing with @spacegliderrrr, the responsibility for actions taken through the `createPoolNew` function and anything within the `admin.sol` contract falls under the admin's purview. This perspective is reinforced by the common practice in IDOs or presales, where the admin and their team are responsible for setting up protocols on launchpads. Furthermore, the distinction that faults or edge cases created by users are typically considered low severity according to Sherlock's rules highlights the importance of distinguishing between admin-level and user-level actions in assessing issue severity and responsibility.

**Comment by 0xDenzi** [comment]
@Hash01011122 while I do agree with what you've said about IDOs or presales but I believe this is a different case. Just stating for more clarity that there exists two types of `admin.sol` in the codebase. My submission talks about the permissionless version of `admin.sol`
 
1.  `admin.sol` from `zap-contracts-lab` : This is the curated version where everything within this contract falls under the admin's purview like you've stated. All of the functions here are under the admin's authority. [Zap Labs](https://zap-2.gitbook.io/zaponblast/protocol-overview/zap-labs)

2. `admin.sol` from `zap-launches-contracts` : This is the permissionless version where not everything falls under the admin's purview. This contract serves users to create their own token sales themselves without needing the expertise/supervision of admins to help and manage their token sale's. It is up to users to set up their token sales with their own configurations (parameters). This submission is mentioning this `admin.sol`. [Zap Launches](https://zap-2.gitbook.io/zaponblast/protocol-overview/zap-launch)

Regarding User Input Validation, from sherlock's doc we have 

> User input validation: User input validation to prevent user mistakes is not considered a valid issue. However, if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high. [Example(Valid)](https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/47)

I believe this submission is a valid high as it allows users to create malicious pools where other user's can deposit but not withdraw any claimable asset, These pools which are created through the permissionless `admin.sol` lock the depositor's funds indefinitely and most of the functions are not executable due to reverts breaking core contract functionality.

**Comment by omar-ahsan** [comment]
@Evert0x can you take a look at this?

**Comment by 0xDenzi** [comment]
@Hash01011122 @Evert0x @Czar102 pinging for a response on why this is not being considered. Everything has been provided related to the submission and I have not received feedback from the judge after my last comment.

P.S I did not meet the eligibility criteria for escalations because this is my first contest on sherlock where I submitted issues.

**Comment by 0xDenzi** [comment]
@Hash01011122

**Comment by ghost** [comment]
I standby what I said earlier. Furthermore, even in the scenario where Zap deploys a permissionless version of `admin.sol` (which is typically not the case), the protocol can redeploy its pool without any fund loss or contract bricking. If your assumption is that the protocol will utilize a permissionless version of `admin.sol`, it's inaccurate because the presence of trusted admins running the protocol would be pointless. Could you please specify the attack vector and explain why you consider this a high finding demonstrating loss of funds or bricking of contract?

**Comment by 0xDenzi** [comment]
> even in the scenario where Zap deploys a permissionless version of `admin.sol` (which is typically not the case)

Zap are deploying a version of admin.sol through which any user can create a pool. Let me clear this through the scope of the contest
![Screenshot 2024-04-16 100352](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/assets/106596821/e8e8fa81-9d30-49ce-8b56-16648a0f0800)

There exists two `admin.sol`, Both have admin functionalities but there is one major difference which is explained below.

> it's inaccurate because the presence of trusted admins running the protocol would be pointless.

As you can see there are 2 versions of `admin.sol`. Both contracts contain the functionality to create new token sales but the main difference is that only admin/operator can create token sales in the `labs` folder while any user can create token sales in the `launches` folder. The difference exists in the `createPoolNew()` function which is present in both `admin.sol`, further more to support the creation of pools by any user, there is an additional function `_checkingParams()` in the `launches/admin.sol` contract. This function does not need to be present in the labs `admin.sol` because the admins are in control of all functions.

1. In Labs [admin.sol](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/Admin.sol#L295-L317) the function `createPoolNew()` has a role check which checks for the role of the msg.sender who should be operator/admin. This means only trusted users are allowed to create token sales through here. The admins and operators in this contract will be creating and managing token sales on behalf of other users.


2. In Launches [admin.sol](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-launches-contracts/contracts/Admin.sol#L288-L315) the function `createPoolNew()` does not have a role check, I or any other user can simply call this function and use it to create a token sale. That is why there is `_checkingParams()` function in this admin.sol. That function is used to validate user inputs so that proper IDOs can be created. This is the `permissionless` feature of this contract. Admins do not oversee the token sale creation here. This is a feature of the protocol to allow users like me or you to promote token sales for our tokens with our own configuration.

The vector is straight forward

1. Suppose Bob calls the `createPoolNew()` function with all valid parameters except the `maxAllocation` and `_params.liqudityPercentage`. `maxAllocation` is inputted as 9999 or below and `_params.liqudityPercentage` is wrongly given.
2. `_checkingParams()` is used to validate the user inputs but since it does not check `maxAllocation` or `_params.liqudityPercentage`, a faulty/scammy pool is created.
3. On initializing the token price will be set to 0.
4. Alice deposits into the token sale so she can get a share of the tokens that are being sold.
5. Bob knows that the takeUSDBRaised() will never execute because of Case 1 and Case 2 as mentioned in the submission. Since this function reverts the variable `isRaiseClaimed` will never be set to true.
6. The variable `isRaiseClaimed` should always be true if any user wants to claim their tokens, but since it can never be set to true. Many of the functions such as claim(), addLiq(), claimLP(), vesting() will revert.

The funds for all users are locked inside and contract is bricked. The PoC in the submission can be used to verify these steps. The sponsors have also confirmed this to be valid and a gap in `_checkingParams()` function.

**Comment by ghost** [comment]
Hey, I don't think any of the point your mentioning will result in attack in real life scenario as no permissionless `admin.sol` will be used for operational event. Your entire issue emerges from input validation from permissionless `admin.sol` which in itself is invalid. Even when on first glance of reading report I considered it valid too but sponsors and lead senior watson confirmed that it isn't possible that protocol will be using any permissionless `admin.sol` to create any Newpool for IDO's

**Comment by 0xDenzi** [comment]
@Hash01011122 with all due respect, The lead senior watson's words do not count against the contest's description which itself mentions that the zap protocol offers curated (under admin control) and permissionless token sales, the sponsors have mentioned in the discord public chat explicitly that the zap-launches-contract is a permissionless environment for users to create their own token sales on our launchpad.

![Screenshot 2024-04-16 173316](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/assets/106596821/38fd7191-5acf-478c-a9ca-17447b5db4a2)

![Screenshot 2024-04-16 172656](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/assets/106596821/0a25c0d9-a807-4491-97f4-ac124293aa6a)

The `admin.sol` in the permissionless environment has one function that any user can use to launch their own token sales on the launchpad. It is the function to create new token sales. This is operational and we were given this repo's `admin.sol` to audit. 

Regarding input validation, sherlock's docs mention 

>User input validation to prevent user mistakes is not considered a valid issue. However, if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high. [Example(Valid)](https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/47)

My issue is not a basic user mistake, It causes significant impact for any user that interacts with such created pool. Neither Hierarchy of truth makes this submission invalid nor does user input mistake according to the docs provided.

**Comment by 0xnirlin** [comment]
@Hash01011122 there are two admin.sol here, one is permissioned and other is pemissionless, permissionless is also in scope as we can see in above screenshot. Which means protocol plans to utilize the permissionless admin at some point, so the pool created via permissionless admin should never allow creating malicious pool. WDYT?

The point here is in permissionless scnerio there is no admin, every user can create pool. It would have been an admin mistake in case of permissioned contract only.

**Comment by ghost** [comment]
It would be better if someone with deeper knowledge of protocols documentation and codebase can shed some insight on this issue. Tagging @deadrosesxyz, @detectiveking123 and @spacegliderrrr

**Comment by detectiveking123** [comment]
@Hash01011122 I agree with you

**Comment by 0xnirlin** [comment]
@Hash01011122 I think it's the lead judge's responsibility to assess the right severity of the issue and understand the component related to it, asking others except for LSW(not optimal either) is a bad option IMO, since the resulting outcome could affect them too.

The only reasonable party to confirm it from is the protocol team, which apparently agrees this is an issue and should be fixed. 

@detectiveking123 since you replied, it would have been better if you came up with a factual counter argument explaining how the issue with a permissionless component is also an admin error (which is not because permissionless is not operated by admin)

**Comment by ghost** [comment]
Here's the take of @deadrosesxyz:
> The DoS happens in the logic of contracts TokenSaleETH and TokenSaleUSDB which are not in scope in the audit contest
It requires user mistake

And I agree with things he mentioned, Still waiting for protocols confirmation regarding this one but to me its low severity issue. I will tag here head of judging @Evert0x and inform him to comment on this issue

**Comment by 0xDenzi** [comment]
> The DoS happens in the logic of contracts TokenSaleETH and TokenSaleUSDB which are not in scope in the audit contest

The DoS issues occur in the TokenSaleETH and TokenSaleUSDB contracts, but it seems the main point has been overlooked. Both `admin.sol` contracts contain similar functions. Conducting audits on both would have been redundant due to their similar functionalities. However, a comparison reveals that the majority of the functions are identical, with only two major exceptions: `_checkingParams()` and `createPoolNew()`.

In my opinion, the sponsors aimed to have the permissionless component of the `zap-launches-contract's admin.sol` audited specifically to verify the creation of pools by any user. Since these two functions are in scope, and malicious or faulty pools can be created due to improper implementations of these functions, and the mitigation applies in  `_checkingParams()` or `createPoolNew()` suggests that this is not a straightforward case of being out of scope.

> It requires user mistake

I am going to be repeat what the sherlocks docs mention

> User input validation: User input validation to prevent user mistakes is not considered a valid issue. However, if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high. [Example(Valid)](https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/47)

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
