### ISSUE TITLE
Varun_05 - Users can get back their whole taxAmount whenever state.totalPrivateSold > (state.totalSupplyInValue)

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zap-protocol-judging#159]
Varun_05

high

# Users can get back their whole taxAmount whenever state.totalPrivateSold > (state.totalSupplyInValue)

## Summary
Users can cleverly deposit large number of tokens i.e upto their maxAllocation so that state.totalPrivateSold > (state.totalSupplyInValue) and as this happens they are eligible to claim their shares back and as well as their whole tax amount .So if a user wanted to only deposit some amount of tokens but now as they know that after totalPrivateSold exceeds totalSupplyvalue they would get their excess shares and wholetaxAmount if they deposit tokens in a way that makes the taxFreeAllc >= s.share. The users can view the values of both totalPrivateSold and totalSupplyInValue through view function.

## Vulnerability Detail
Lets understand the flow 
First deposit is called by the users which main function here is the _processPrivate function which is as follows 
```solidity
function _processPrivate(address _sender, uint256 _amount) internal {
        require(_amount > 0, "TokenSale: Too small");

        Staked storage s = stakes[_sender];
        uint256 amount = _amount * PCT_BASE;
        uint256 sum = s.amount + amount;

        uint256 maxAllocationOfUser = (calculateMaxAllocation(_sender)) *
            PCT_BASE;
        require(sum <= maxAllocationOfUser, "upto max allocation");
        uint256 taxFreeAllcOfUser = 0; // hardcode zero - all pools have ax

        uint256 userTaxAmount;

        if (sum > taxFreeAllcOfUser) {
            uint256 userTxRate = userTaxRate(sum, _sender);
            if (s.amount < taxFreeAllcOfUser) {
                userTaxAmount =
                    ((sum - taxFreeAllcOfUser) * userTxRate) /
                    POINT_BASE;
            } else {
                userTaxAmount = (amount * userTxRate) / POINT_BASE;
            }
        }

        if (userTaxAmount > 0) {
            s.taxAmount += userTaxAmount;
            usdc.safeTransferFrom(_sender, marketingWallet, userTaxAmount);
        }
        s.amount += uint128(amount);
        state.totalPrivateSold += uint128(amount);
        usdc.safeTransferFrom(_sender, address(this), amount);

        /**@notice Forbid unstaking*/
        // stakingContract.setPoolsEndTime(_sender, uint256(params.privateEnd)); // TODO: uncomment
        emit DepositPrivate(_sender, _amount, address(this));
    }
```
According to the implementation  uint256 taxFreeAllcOfUser = 0
A user has to pay tax for every amount of tokens they deposit which is equal to the following userTaxAmount = (amount * userTxRate) / POINT_BASE

Now a situation arises when the  state.totalPrivateSold = (state.totalSupplyInValue) so if  now users deposit tokens such that  for exmple state.totalPrivateSold = 2*(state.totalSupplyInValue) and now the tokenSale is finished.
So now users eligible to call the claim function.
```solidity
function claim() external {
        checkingEpoch();
        require(
            uint8(epoch) > 1 && !admin.blockClaim(address(this)),
            "TokenSale: Not time or not allowed"
        );

        Staked storage s = stakes[msg.sender];
        require(s.amount != 0, "TokenSale: No Deposit");
        require(!s.claimed, "TokenSale: Already Claimed");

        uint256 left;
        (s.share, left) = _claim(s);
        require(left > 0, "TokenSale: Nothing to claim");
        uint256 refundTaxAmount;
        if (s.taxAmount > 0) {
            uint256 tax = userTaxRate(s.amount, msg.sender);
            uint256 taxFreeAllc = _maxTaxfreeAllocation(msg.sender) * PCT_BASE;
            if (taxFreeAllc >= s.share) {
                refundTaxAmount = s.taxAmount;
            } else {
                refundTaxAmount = (left * tax) / POINT_BASE;
            }
            usdc.safeTransferFrom(marketingWallet, msg.sender, refundTaxAmount);
        }
        s.claimed = true;
        usdc.safeTransfer(msg.sender, left);
        emit Claim(msg.sender, left);
    }
```
Main calculation is done in the following function  (s.share, left) = _claim(s);
```solidity
function _claim(Staked memory _s) internal view returns (uint120, uint256) {
        uint256 left;
        if (state.totalPrivateSold > (state.totalSupplyInValue)) {
            uint256 rate = (state.totalSupplyInValue * PCT_BASE) /
                state.totalPrivateSold;
            _s.share = uint120((uint256(_s.amount) * rate) / PCT_BASE);
            left = uint256(_s.amount) - uint256(_s.share);
        } else {
            _s.share = uint120(_s.amount);
        }

        return (_s.share, left);
    }
```
So as we have assumed state.totalPrivateSold = 2*(state.totalSupplyInValue) 

so rate = 1/2(neglecting decimals as of now otherwise 5e17)
so now _s.share = 1/2(_s.amount)
left = 1/2(_s.amount)
(Just using some values obviously it can differ)

Now lets look at the following lines which are important 
```solidity
if (s.taxAmount > 0) {
            uint256 tax = userTaxRate(s.amount, msg.sender);
            uint256 taxFreeAllc = _maxTaxfreeAllocation(msg.sender) * PCT_BASE;
            if (taxFreeAllc >= s.share) {
                refundTaxAmount = s.taxAmount;
            } else {
                refundTaxAmount = (left * tax) / POINT_BASE;
            }
            usdc.safeTransferFrom(marketingWallet, msg.sender, refundTaxAmount);
        }
```
As tax is paid for every deposit s.taxAmount would obviously be true
Now taxFreeAllc is calculated using the _maxTaxFreeAllocation function so assume it returns some value
Now issue lies in the if condition 
as we can see if taxFreeAllc >= s.share user if refunded whole s.taxAmount , as initially when a user calls deposit function he pays tax for whole amount of tokens because it was hardcoded  taxFreeAllcOfUser = 0 but now taxFreeAllc is taken into account so now users can carefully deposit tokens so that state.totalPrivateSold  becomes greater than (state.totalSupplyInValue) and such a ratio is acheived such that taxFreeAllc >= s.share and they get their taxAmount back and also deposit tokens.Now not only they get back their full taxAmount back they also reduce the share amount of other users and for those users whose taxFreeAllc < s.share they only get refundTaxAmount = (left * tax) / POINT_BASE which is correct according to the current implementation.

It is a logical error in the code because first they assume that user has to pay tax for every deposit but in claim they take into account taxFreeAllocation thus allowing users to not pay tax and get shares(deposit tokens) . This also can impact the protocol as some users can get back full tax amount instead they should only get back the tax which was applied to left amount. The above code is correct if initially in deposit function they hadn't hardcoded taxFreeAllocUser = 0 but it is not the case in the current codebase.
## Impact
Users can pay no tax amount and also reduce shares of other users.
## Code Snippet
https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L383
## Tool used

Manual Review

## Recommendation
refundTaxAmount should be equal to (left * tax) / POINT_BASE  in either cases because of the hardcoded taxFreeValue = 0

**Comment by vsharma4394** [comment]
I believe it is a logical error becasue initially there was not taxfreeAllocation but then if privateSoldValue is greater than totalSppuly then taxFreeAllocation was takenInto account which can cause some users to get full tax refund whereas others not ,so some logical error.

**Comment by vsharma4394** [comment]
Can someone escalate this issue please

**Comment by ghost** [comment]
This is duplicate of #58 @Czar102

**Comment by deadrosesxyz** [comment]
@Hash01011122 this is not a duplicate in any way? #58 explains that if token does not oversell, users cannot get the tax refund they're deserved. Not only this is never mentioned here, but this submission also shows no issue, rather states expected behavior.

**Comment by ghost** [comment]
@deadrosesxyz I agree with you that it doesn't thoroughly explains entire root cause but it points the same issue as #58 for which I am inclined to consider it as duplicate of #58.

**Comment by deadrosesxyz** [comment]
Would you mind elaborating on that - where does it point the same issue? It honestly does not point to any issue. Everything the user says is that if token is overselling  and user spends no more than their tax-free allocation they'll not be paying tax. What they're saying is basically contract's working as expected

**Comment by ghost** [comment]
The **watson** attempted to highlight the problem but did not successfully identify the underlying cause or provide an attack vector. Observing the sponsors' confirmed tag led to an oversight in fully assessing the issue against the complete checklist. Upon closer examination and thorough review, the conclusion is that the issue should indeed be considered invalid. 

If @vsharma4394 feels this is valid:
- Watson should point out root cause in his report and explain it here.
- Watson should be able to clearly show if there is any attack path.

**Comment by vsharma4394** [comment]
@Hash01011122 taxFreeAlloc is taken as zero has caused different interpretation of the code i am not saying @deadrosesxyz is wrong but neither am I. Firstly making taxFreeAlloc as zero causes users to pay tax on whole amount not considering taxFreeAllocation. As taxFreeAlloc is zero intially so the users should not be considered for taxFreeAmount while calling claim function which makes sense becasue taxffreeAlloc was zero. Now in the following code
```solidity
 if (s.taxAmount > 0) {
            uint256 tax = userTaxRate(s.amount, msg.sender);
            uint256 taxFreeAllc = _maxTaxfreeAllocation(msg.sender) * PCT_BASE;
            if (taxFreeAllc >= s.share) {
                refundTaxAmount = s.taxAmount;
            } else {
                refundTaxAmount = (left * tax) / POINT_BASE;
            }
            usdc.safeTransferFrom(marketingWallet, msg.sender, refundTaxAmount);
        }
```
Why should we consider taxFreeAlloc is protocol doesn't consider taxFreeAlloc intially.

Now in order to support my finding 
1.First user pay whole tax.
2. If token doesn't oversell not taxFreeAlloc is taken into account , because of taxFreeAlloc =0.
3. Now if token oversells then some users are given taxRefund on taking into consideration taxFreeAlloc which as follows
 if (taxFreeAllc >= s.share) {
                refundTaxAmount = s.taxAmount; others are refunded on the left amount.
4. My point is that taxFree logic should never be taken into account because of taxFreeAlloc eqaul to zero, and sponsers agree with my point so due to which thius finding should be valid.
5. Also if tokens doesn't oversells user doesn't get refund which makes overselling token profitable for user so they would always be inclined to do so, which is not a ideal situation for other users who would have more shares hadn't he token oversell.
6. If taxFreeAlloc was not taken into consideration user wouldn't be inclined to buy more tokens beyond its limit.


If initially taxFreeAlloc was not hardcoded as zero then all these issues would not have arised. My finding is correct because it follows the code consistency.

In short I am saying taxFreeAlloc should not be considered in claim function becasue taxFreeAlloc was taken as zero.
If taxFreeAlloc was not zero then my finding would have be surely wrong.

**Comment by vsharma4394** [comment]
If sponsers have been active in the contest these issues wouldn't have arised. Best scenario would be considering all findings be valid because of different interepretation of code and neither i and nor @deadrosesxyz is wrong.

**Comment by vsharma4394** [comment]
@deadrosesxyz understanding of the code neglects the hardcoded value of taxFreeAlloc = 0 . Hadn't that been zero @deadrosesxyz would have been correct but currently i am right. #58 is not a duplicate of this issue and should not be valid.

**Comment by vsharma4394** [comment]
> The protocol team fixed this issue in PR/commit https://github.com/Lithium-Ventures/zap-contracts-labs/pull/3.

@Hash01011122 sponsers have also confirmed my issue, so i don't think so that my finding is invalid.

**Comment by ghost** [comment]
I interpret your issue as follows: a user is entitled to a full tax refund only if their tax-free allocation exceeds the s.share amount, which is the actual amount of funds used. This condition would render the issue invalid. But would like to know your thoughts @deadrosesxyz @niketansainiantier

**Comment by vsharma4394** [comment]
> I interpret your issue as follows: a user is entitled to a full tax refund only if their tax-free allocation exceeds the s.share amount, which is the actual amount of funds used. This condition would render the issue invalid. But would like to know your thoughts @deadrosesxyz @niketansainiantier

No my issue is as follows, user should never get full tax refund even if tax free allocation exceeds s.share amount because initially they paid tax on full amount even if they had tax free allocation initially because currently protocol tax is charged for whole amount. And currently a user can deliberately cause totalPrivareSold to be greater than totalSupplyValue and when this happens shares of every user is reduced, so a use can cleverly cause there shares to reduce by amount which causes their shares to be less than taxFreeAllocation thus getting refunded whole tax amount this bypassing initially condition where taxFreeAllocation was hardcoded to zero.

**Comment by vsharma4394** [comment]
Whole point of hardcoding taxFreeAllocation to zero initially is take tax on whole amount irrespective of user having taxFreeAllocation. Thr sponsers hardcoded taxFreeAllocation to zero while depositing but didn't make the essential changes to the claim function, that is why they have now changed their code which is recommended in the this issue.

**Comment by vsharma4394** [comment]
@Hash01011122 can you provide last feedback.
